name: huawei2024
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - mindspore==2.9.0
      - torch==2.12.1
      - torchvision
      - torchaudio
      - numpy<2.0.0
      - pandas
      - scikit-learn
      - matplotlib
      - jupyter
      - notebook
      - ipykernel
